service: nsartech-money-vault-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, 'eu-west-2'}
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221
  environment:
    TRUE_LAYER_API_URL: ${env:TRUE_LAYER_API_URL}
    TRUE_LAYER_CLIENT_ID: ${env:TRUE_LAYER_CLIENT_ID}
    TRUE_LAYER_CLIENT_SECRET: ${env:TRUE_LAYER_CLIENT_SECRET}
    TRUE_LAYER_REDIRECT_URL: ${env:TRUE_LAYER_REDIRECT_URL}
    ENVIRONMENT: ${self:provider.stage}
    NODE_ENV: ${env:NODE_ENV}
    DB_HOST: ${env:DB_HOST}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_DATABASE: ${env:DB_DATABASE}

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 3001

functions:
  starlingAuth:
    handler: build/src/functions/trueLayer.authCallback
    events:
      - http:
          path: /api/authCallback
          method: get
  getProviders:
    handler: build/src/functions/provider.getProviders
    events:
      - http:
          path: /api/providers
          method: get