service: nsartech-money-vault-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, 'eu-west-2'}
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221
  environment:
    TRUE_LAYER_API_URL: ${env:TRUE_LAYER_API_URL}
    TRUE_LAYER_CLIENT_ID: ${env:TRUE_LAYER_CLIENT_ID}
    TRUE_LAYER_CLIENT_SECRET: ${env:TRUE_LAYER_CLIENT_SECRET}
    TRUE_LAYER_REDIRECT_URL: ${env:TRUE_LAYER_REDIRECT_URL}

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 3001

functions:
  starlingAuth:
    handler: src/functions/trueLayer.authCallback
    events:
      - http:
          path: /api/authCallback
          method: get